[functions.create-user]
verify_jwt = true

[functions.kiosk-checkin]
verify_jwt = true

[functions.receive-marketing-order]
verify_jwt = true

[functions.publish-facebook-story]
verify_jwt = true

[functions.publish-facebook-video-story]
verify_jwt = true

[functions.initiate-mobile-money-payment]
verify_jwt = true

[functions.pawapay-webhook]
verify_jwt = false

[functions.initiate-card-payment]
verify_jwt = true

[functions.cinetpay-webhook]
verify_jwt = false
