-- =============================================================
-- Migration: Add missing indexes on foreign key columns
-- Improves JOIN performance and FK constraint enforcement
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_fk_audit_logs_performed_by ON audit_logs (performed_by);
CREATE INDEX IF NOT EXISTS idx_fk_barcodes_baker2_id ON barcodes (baker2_id);
CREATE INDEX IF NOT EXISTS idx_fk_barcodes_baker_id ON barcodes (baker_id);
CREATE INDEX IF NOT EXISTS idx_fk_barcodes_created_by ON barcodes (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_compliance_checks_checked_by ON compliance_checks (checked_by);
CREATE INDEX IF NOT EXISTS idx_fk_compliance_comments_author_id ON compliance_comments (author_id);
CREATE INDEX IF NOT EXISTS idx_fk_compliance_discrepancies_resolved_by ON compliance_discrepancies (resolved_by);
CREATE INDEX IF NOT EXISTS idx_fk_compliance_discrepancies_validated_by ON compliance_discrepancies (validated_by);
CREATE INDEX IF NOT EXISTS idx_fk_consignment_returns_consignment_id ON consignment_returns (consignment_id);
CREATE INDEX IF NOT EXISTS idx_fk_consignments_batch_id ON consignments (batch_id);
CREATE INDEX IF NOT EXISTS idx_fk_consignments_created_by ON consignments (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_delivery_batches_created_by ON delivery_batches (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_delivery_batches_pot_type_id ON delivery_batches (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_delivery_events_performed_by ON delivery_events (performed_by);
CREATE INDEX IF NOT EXISTS idx_fk_delivery_events_sales_point_id ON delivery_events (sales_point_id);
CREATE INDEX IF NOT EXISTS idx_fk_delivery_expenses_sales_point_id ON delivery_expenses (sales_point_id);
CREATE INDEX IF NOT EXISTS idx_fk_deposits_qr_code_id ON deposits (qr_code_id);
CREATE INDEX IF NOT EXISTS idx_fk_dough_batches_created_by ON dough_batches (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_dough_deliveries_created_by ON dough_deliveries (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_ingredients_created_by ON ingredients (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_kneaders_profile_id ON kneaders (profile_id);
CREATE INDEX IF NOT EXISTS idx_fk_leave_periods_created_by ON leave_periods (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_leave_periods_notified_to ON leave_periods (notified_to);
CREATE INDEX IF NOT EXISTS idx_fk_leave_periods_substitute_driver_id ON leave_periods (substitute_driver_id);
CREATE INDEX IF NOT EXISTS idx_fk_opportunistic_sales_pot_type_id ON opportunistic_sales (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_personnel_change_requests_adjoint_approved_by ON personnel_change_requests (adjoint_approved_by);
CREATE INDEX IF NOT EXISTS idx_fk_personnel_change_requests_admin_approved_by ON personnel_change_requests (admin_approved_by);
CREATE INDEX IF NOT EXISTS idx_fk_personnel_change_requests_directrice_approved_by ON personnel_change_requests (directrice_approved_by);
CREATE INDEX IF NOT EXISTS idx_fk_personnel_change_requests_rejected_by ON personnel_change_requests (rejected_by);
CREATE INDEX IF NOT EXISTS idx_fk_personnel_change_requests_requested_by ON personnel_change_requests (requested_by);
CREATE INDEX IF NOT EXISTS idx_fk_production_records_created_by ON production_records (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_production_records_dough_delivery_id ON production_records (dough_delivery_id);
CREATE INDEX IF NOT EXISTS idx_fk_production_records_pot_type_id ON production_records (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_qr_codes_created_by ON qr_codes (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_qr_codes_pot_type_id ON qr_codes (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_quota_payments_collected_by ON quota_payments (collected_by);
CREATE INDEX IF NOT EXISTS idx_fk_receivable_payments_collected_by ON receivable_payments (collected_by);
CREATE INDEX IF NOT EXISTS idx_fk_receivable_payments_receivable_id ON receivable_payments (receivable_id);
CREATE INDEX IF NOT EXISTS idx_fk_receivables_batch_id ON receivables (batch_id);
CREATE INDEX IF NOT EXISTS idx_fk_restock_requests_pot_type_id ON restock_requests (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_restock_requests_requested_by ON restock_requests (requested_by);
CREATE INDEX IF NOT EXISTS idx_fk_restock_requests_sales_point_id ON restock_requests (sales_point_id);
CREATE INDEX IF NOT EXISTS idx_fk_restock_requests_treated_by ON restock_requests (treated_by);
CREATE INDEX IF NOT EXISTS idx_fk_returns_sales_point_id ON returns (sales_point_id);
CREATE INDEX IF NOT EXISTS idx_fk_sales_points_created_by ON sales_points (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_sales_points_driver_id ON sales_points (driver_id);
CREATE INDEX IF NOT EXISTS idx_fk_stock_handovers_batch_id ON stock_handovers (batch_id);
CREATE INDEX IF NOT EXISTS idx_fk_stock_handovers_performed_by ON stock_handovers (performed_by);
CREATE INDEX IF NOT EXISTS idx_fk_stock_handovers_pot_type_id ON stock_handovers (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_stock_handovers_production_record_id ON stock_handovers (production_record_id);
CREATE INDEX IF NOT EXISTS idx_fk_stock_movements_created_by ON stock_movements (created_by);
CREATE INDEX IF NOT EXISTS idx_fk_wedding_orders_pot_type_id ON wedding_orders (pot_type_id);
CREATE INDEX IF NOT EXISTS idx_fk_work_schedules_created_by ON work_schedules (created_by);
